services:
  flserver:
    hostname: flserver
    env_file: .env
    build: flserver/
    restart: unless-stopped
    image: ronaldvk90/flserver:latest
    ports:
      - "3389:3389"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./freelancer:/freelancer
      - flhome:/home
  samba:
    env_file: .env
    build: samba/
    restart: unless-stopped
    image: ronaldvk90/samba:latest
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./freelancer:/freelancer
volumes:
  flhome:
