services:

  flserver:
    hostname: flserver
    env_file: .env
    build: .
    restart: unless-stopped
    image: ronaldvk90/flserver:latest
    ports:
      - "3389:3389"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./freelancer:/freelancer
      - flhome:/home

volumes:
  flhome:
