services:
  flserver:
    env_file: environment.env
    build: .
    restart: unless-stopped
    image: flserver:1.3
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./freelancer:/freelancer
      - flhome:/home
volumes:
  flhome:
    external: false
